const tennisRankings = [
  {
    rank: 1,
    name: "Novak Djokovic",
    country_name: "Serbia",
    country_id: "SRB",
    points: 11830,
    bestRank: 1,
    bestRankDate: "2011-07-04",
    rankDiff: 0,
    pointsDiff: 90,
    bestPoints: 16950,
  },
  {
    rank: 2,
    name: "Rafael Nadal",
    country_name: "Spain",
    country_id: "ESP",
    points: 9850,
    bestRank: 1,
    bestRankDate: "2008-08-18",
    rankDiff: 0,
    pointsDiff: 0,
    bestPoints: 15390,
  },
  {
    rank: 3,
    name: "Dominic Thiem",
    country_name: "Austria",
    country_id: "AUT",
    points: 9125,
    bestRank: 3,
    bestRankDate: "2020-03-02",
    rankDiff: 0,
    pointsDiff: 0,
    bestPoints: 9125,
  },
  {
    rank: 4,
    name: "Roger Federer",
    country_name: "Switzerland",
    country_id: "SUI",
    points: 6630,
    bestRank: 1,
    bestRankDate: "2004-02-02",
    rankDiff: 0,
    pointsDiff: 0,
    bestPoints: 12315,
  },
  {
    rank: 5,
    name: "Daniil Medvedev",
    country_name: "Russian Federation",
    country_id: "RUS",
    points: 5980,
    bestRank: 4,
    bestRankDate: "2019-09-09",
    rankDiff: 1,
    pointsDiff: 90,
    bestPoints: 5980,
  },
  {
    rank: 6,
    name: "Stefanos Tsitsipas",
    country_name: "Greece",
    country_id: "GRE",
    points: 5925,
    bestRank: 5,
    bestRankDate: "2019-08-05",
    rankDiff: -1,
    pointsDiff: 0,
    bestPoints: 5925,
  },
  {
    rank: 7,
    name: "Alexander Zverev",
    country_name: "Germany",
    country_id: "GER",
    points: 5015,
    bestRank: 3,
    bestRankDate: "2017-11-06",
    rankDiff: 0,
    pointsDiff: 0,
    bestPoints: 6630,
  },
  {
    rank: 8,
    name: "Andrey Rublev",
    country_name: "Russian Federation",
    country_id: "RUS",
    points: 3839,
    bestRank: 8,
    bestRankDate: "2020-10-19",
    rankDiff: 0,
    pointsDiff: 410,
    bestPoints: 3839,
  },
  {
    rank: 9,
    name: "Diego Sebastian Schwartzman",
    country_name: "Argentina",
    country_id: "ARG",
    points: 3285,
    bestRank: 8,
    bestRankDate: "2020-10-12",
    rankDiff: 0,
    pointsDiff: 0,
    bestPoints: 3285,
  },
  {
    rank: 10,
    name: "Matteo Berrettini",
    country_name: "Italy",
    country_id: "ITA",
    points: 3075,
    bestRank: 8,
    bestRankDate: "2019-11-04",
    rankDiff: 0,
    pointsDiff: 0,
    bestPoints: 3075,
  },
  {
    rank: 11,
    name: "Gael Monfils",
    country_name: "France",
    country_id: "FRA",
    points: 2860,
    bestRank: 6,
    bestRankDate: "2016-11-07",
    rankDiff: 0,
    pointsDiff: 0,
    bestPoints: 3815,
  },
  {
    rank: 12,
    name: "Denis Shapovalov",
    country_name: "Canada",
    country_id: "CAN",
    points: 2830,
    bestRank: 10,
    bestRankDate: "2020-09-21",
    rankDiff: 0,
    pointsDiff: 0,
    bestPoints: 2830,
  },
  {
    rank: 13,
    name: "Roberto Bautista Agut",
    country_name: "Spain",
    country_id: "ESP",
    points: 2710,
    bestRank: 9,
    bestRankDate: "2019-11-04",
    rankDiff: 0,
    pointsDiff: 0,
    bestPoints: 2710,
  },
  {
    rank: 14,
    name: "David Goffin",
    country_name: "Belgium",
    country_id: "BEL",
    points: 2555,
    bestRank: 7,
    bestRankDate: "2017-11-20",
    rankDiff: 0,
    pointsDiff: 0,
    bestPoints: 3775,
  },
  {
    rank: 15,
    name: "Pablo Carreno Busta",
    country_name: "Spain",
    country_id: "ESP",
    points: 2400,
    bestRank: 10,
    bestRankDate: "2017-09-11",
    rankDiff: 0,
    pointsDiff: 0,
    bestPoints: 2855,
  },
  {
    rank: 16,
    name: "Fabio Fognini",
    country_name: "Italy",
    country_id: "ITA",
    points: 2400,
    bestRank: 9,
    bestRankDate: "2019-07-15",
    rankDiff: 0,
    pointsDiff: 0,
    bestPoints: 2920,
  },
  {
    rank: 17,
    name: "Milos Raonic",
    country_name: "Canada",
    country_id: "CAN",
    points: 2265,
    bestRank: 3,
    bestRankDate: "2016-11-21",
    rankDiff: 0,
    pointsDiff: 0,
    bestPoints: 5450,
  },
  {
    rank: 18,
    name: "Grigor Dimitrov",
    country_name: "Bulgaria",
    country_id: "BUL",
    points: 2260,
    bestRank: 3,
    bestRankDate: "2017-11-20",
    rankDiff: 2,
    pointsDiff: 45,
    bestPoints: 5150,
  },
  {
    rank: 19,
    name: "Karen Khachanov",
    country_name: "Russian Federation",
    country_id: "RUS",
    points: 2245,
    bestRank: 8,
    bestRankDate: "2019-07-15",
    rankDiff: -1,
    pointsDiff: 0,
    bestPoints: 2990,
  },
  {
    rank: 20,
    name: "Stan Wawrinka",
    country_name: "Switzerland",
    country_id: "SUI",
    points: 2230,
    bestRank: 3,
    bestRankDate: "2014-01-27",
    rankDiff: -1,
    pointsDiff: 0,
    bestPoints: 6865,
  },
];
